// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Collections.Generic;

namespace TuDuShareDemo
{
	public partial class DemoTableViewCell : UITableViewCell
	{
		public static readonly NSString Key = new NSString ("DemoTableViewCell");

		public DemoTableViewCell (IntPtr handle) : base (handle)
		{
		}

		public void Populate (Dictionary<string, string> item)
		{
			cellLabel.Text = item["label"];
			cellImageView.Image = UIImage.FromBundle (item ["image"]);
		}
	}
}
